public enum ArchiveToolDefinitions {
    /// MCP-compatible tool schemas for all archive operations.
    /// Consumed by MCP server (tools/list) and by native clients (e.g. Navi).
    public static let all: [[String: Any]] = [
        [
            "name": "archive_add",
            "description": "Add a FITS file or directory of FITS files to the astrophoto archive. Reads metadata from FITS headers automatically.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "path": [
                        "type": "string",
                        "description": "Absolute path to a FITS file or directory.",
                    ],
                    "recursive": [
                        "type": "boolean",
                        "description": "Recurse into subdirectories (when path is a directory). Default false.",
                    ],
                ] as [String: Any],
                "required": ["path"],
            ] as [String: Any],
        ],
        [
            "name": "archive_search",
            "description": "Search the archive for frames, frame sets, or both. Equivalent to Finder search — returns files (frames) and folders (frame sets) together by default. Use kind to restrict to one type.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "kind": [
                        "type": "string",
                        "enum": ["both", "frames", "framesets"],
                        "description": "What to search: frames, framesets, or both (default: both).",
                    ],
                    "object_name": ["type": "string", "description": "Partial object name match (applies to both frames and frame sets)."],
                    "frame_types": [
                        "type": "array",
                        "items": ["type": "string"],
                        "description": "Frame types to include (light, dark, flat, bias, diagnostic). Applies to both.",
                    ],
                    "filters": [
                        "type": "array",
                        "items": ["type": "string"],
                        "description": "Optical filters (Hɑ, SII, OIII, R, G, B, L). Applies to both.",
                    ],
                    "processing_level": [
                        "type": "string",
                        "enum": ["raw", "calibrated", "stacked", "stretched"],
                        "description": "Filter by processing level. Applies to both.",
                    ],
                    "camera": ["type": "string", "description": "Camera name, exact match. Applies to both."],
                    "telescope": ["type": "string", "description": "Telescope name, exact match (FITS TELESCOP). Applies to both."],
                    "site": ["type": "string", "description": "Observatory site name, exact match (FITS OBSERVAT). Applies to both."],
                    "from_date": ["type": "string", "description": "Start date YYYY-MM-DD. Applies to both (date span overlap for frame sets)."],
                    "to_date": ["type": "string", "description": "End date YYYY-MM-DD. Applies to both."],
                    "name": ["type": "string", "description": "Partial match on frame set name (frame sets only)."],
                    "min_focal_length": ["type": "number", "description": "Frames only: focal length ≥ this value (mm)."],
                    "max_focal_length": ["type": "number", "description": "Frames only: focal length ≤ this value (mm)."],
                    "min_aperture": ["type": "number", "description": "Frames only: telescope aperture ≥ this value (mm, FITS APTDIA)."],
                    "max_aperture": ["type": "number", "description": "Frames only: telescope aperture ≤ this value (mm, FITS APTDIA)."],
                    "min_pixel_size": ["type": "number", "description": "Frames only: physical (unbinned) pixel size ≥ this value (µm)."],
                    "max_pixel_size": ["type": "number", "description": "Frames only: physical (unbinned) pixel size ≤ this value (µm)."],
                    "binning": ["type": "integer", "description": "Frames only: pixel binning factor, exact match (FITS XBINNING; 1 = unbinned)."],
                    "gain": ["type": "number", "description": "Frames only: camera gain setting, exact match (FITS GAIN)."],
                    "offset": ["type": "number", "description": "Frames only: camera offset/pedestal setting, exact match (FITS OFFSET/PEDESTAL)."],
                    "min_exposure": ["type": "number", "description": "Frames only: exposure time ≥ this value (seconds)."],
                    "max_exposure": ["type": "number", "description": "Frames only: exposure time ≤ this value (seconds)."],
                    "is_master": ["type": "boolean", "description": "Frames only: when true return only master calibration frames; when false exclude them."],
                    "session_id": ["type": "string", "description": "Frames only: return only frames that belong to this observing session UUID."],
                    "min_pixel_scale": ["type": "number", "description": "Frames only: pixel scale ≥ this value (arcsec/px)."],
                    "max_pixel_scale": ["type": "number", "description": "Frames only: pixel scale ≤ this value (arcsec/px)."],
                    "min_width": ["type": "integer", "description": "Frames only: image width ≥ this value (pixels)."],
                    "max_width": ["type": "integer", "description": "Frames only: image width ≤ this value (pixels)."],
                    "min_height": ["type": "integer", "description": "Frames only: image height ≥ this value (pixels)."],
                    "max_height": ["type": "integer", "description": "Frames only: image height ≤ this value (pixels)."],
                    "bitpix": ["type": "integer", "description": "Frames only: FITS BITPIX bit depth, exact match (e.g. 16, 32, -32)."],
                    "min_egain": ["type": "number", "description": "Frames only: electron conversion factor ≥ this value (e⁻/ADU, FITS EGAIN)."],
                    "max_egain": ["type": "number", "description": "Frames only: electron conversion factor ≤ this value (e⁻/ADU, FITS EGAIN)."],
                    "min_position_angle": ["type": "number", "description": "Frames only: field rotation position angle ≥ this value (degrees east of north)."],
                    "max_position_angle": ["type": "number", "description": "Frames only: field rotation position angle ≤ this value (degrees east of north)."],
                    "added_after": ["type": "string", "description": "Frames only: only frames added to the archive on or after this date (YYYY-MM-DD)."],
                    "added_before": ["type": "string", "description": "Frames only: only frames added to the archive on or before this date (YYYY-MM-DD)."],
                    "max_fwhm": ["type": "number", "description": "Frames only: median FWHM ≤ this value (pixels)."],
                    "min_stars": ["type": "integer", "description": "Frames only: at least this many detected stars."],
                    "max_background_noise": ["type": "number", "description": "Frames only: background noise ≤ this value."],
                    "max_eccentricity": ["type": "number", "description": "Frames only: median star eccentricity ≤ this value (0=circular)."],
                    "max_saturated_star_count": ["type": "integer", "description": "Frames only: at most this many saturated stars."],
                    "max_hot_pixel_count": ["type": "integer", "description": "Frames only: at most this many hot pixels."],
                    "max_sun_altitude": ["type": "number", "description": "Frames only: Sun altitude at capture time ≤ this value (degrees; use -18 for astronomical night)."],
                    "min_moon_separation": ["type": "number", "description": "Frames only: Moon separation from target ≥ this value (degrees)."],
                    "max_moon_illumination": ["type": "number", "description": "Frames only: Moon illumination ≤ this fraction (0–1)."],
                    "stacked": ["type": "boolean", "description": "Frames only: only stacked (master) frames. Shorthand for processing_level=stacked."],
                    "include_rejected": ["type": "boolean", "description": "Frames only: include rejected frames (default false)."],
                    "rejected_only": ["type": "boolean", "description": "Frames only: return only rejected frames."],
                    "ra": ["type": "number", "description": "Frames only: cone search centre RA (degrees)."],
                    "dec": ["type": "number", "description": "Frames only: cone search centre Dec (degrees)."],
                    "radius_deg": ["type": "number", "description": "Frames only: cone search radius (degrees)."],
                    "limit": ["type": "integer", "description": "Frames only: maximum number of frames to return."],
                ] as [String: Any],
                "required": [],
            ] as [String: Any],
        ],
        [
            "name": "archive_get",
            "description": "Show all stored information for a single archive frame by UUID.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Archive frame UUID (from archive_find)."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_list_objects",
            "description": "List all objects in the archive with their frame counts.",
            "inputSchema": [
                "type": "object",
                "properties": [String: Any](),
                "required": [String](),
            ] as [String: Any],
        ],
        [
            "name": "archive_stats",
            "description": "Get archive statistics: frame counts by type/filter, disk usage, and objects.",
            "inputSchema": [
                "type": "object",
                "properties": [String: Any](),
                "required": [String](),
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_inspect",
            "description": "Dry-run: inspect which frames would be included in a frame set and report property distributions (cameras, filters, date span, temperature range, pixel scales, position angles, …) without writing to the database. Use this before archive_frameset_create to check frame compatibility.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "frame_type": ["type": "string", "enum": ["light", "dark", "flat", "bias", "diagnostic"], "description": "Frame type to inspect."],
                    "object_name": ["type": "string", "description": "Partial object name to match (e.g. 'M51')."],
                    "filters": ["type": "array", "items": ["type": "string"], "description": "Optical filters to include (Hɑ, SII, OIII, R, G, B, L)."],
                    "camera": ["type": "string", "description": "Camera name (exact match)."],
                    "telescope": ["type": "string", "description": "Telescope name, exact match (FITS TELESCOP)."],
                    "site": ["type": "string", "description": "Observatory site name, exact match (FITS OBSERVAT)."],
                    "min_focal_length": ["type": "number", "description": "Focal length ≥ this value (mm)."],
                    "max_focal_length": ["type": "number", "description": "Focal length ≤ this value (mm)."],
                    "min_aperture": ["type": "number", "description": "Telescope aperture ≥ this value (mm, FITS APTDIA)."],
                    "max_aperture": ["type": "number", "description": "Telescope aperture ≤ this value (mm, FITS APTDIA)."],
                    "min_pixel_size": ["type": "number", "description": "Physical (unbinned) pixel size ≥ this value (µm)."],
                    "max_pixel_size": ["type": "number", "description": "Physical (unbinned) pixel size ≤ this value (µm)."],
                    "binning": ["type": "integer", "description": "Pixel binning factor, exact match (FITS XBINNING; 1 = unbinned)."],
                    "gain": ["type": "number", "description": "Camera gain setting, exact match (FITS GAIN)."],
                    "offset": ["type": "number", "description": "Camera offset/pedestal setting, exact match (FITS OFFSET/PEDESTAL)."],
                    "min_exposure": ["type": "number", "description": "Exposure time ≥ this value (seconds)."],
                    "max_exposure": ["type": "number", "description": "Exposure time ≤ this value (seconds)."],
                    "from_date": ["type": "string", "description": "Start date YYYY-MM-DD."],
                    "to_date": ["type": "string", "description": "End date YYYY-MM-DD."],
                    "processing_level": ["type": "string", "enum": ["raw", "calibrated", "stacked", "stretched"], "description": "Filter by processing level."],
                    "calibrated": ["type": "boolean", "description": "Only calibrated frames."],
                    "temp_center": ["type": "number", "description": "Centre temperature in °C for dark frame grouping."],
                    "temp_tolerance": ["type": "number", "description": "Temperature tolerance ±°C (default 2.0)."],
                    "min_pixel_scale": ["type": "number", "description": "Pixel scale ≥ this value (arcsec/px)."],
                    "max_pixel_scale": ["type": "number", "description": "Pixel scale ≤ this value (arcsec/px)."],
                    "min_width": ["type": "integer", "description": "Image width ≥ this value (pixels)."],
                    "max_width": ["type": "integer", "description": "Image width ≤ this value (pixels)."],
                    "min_height": ["type": "integer", "description": "Image height ≥ this value (pixels)."],
                    "max_height": ["type": "integer", "description": "Image height ≤ this value (pixels)."],
                    "bitpix": ["type": "integer", "description": "FITS BITPIX bit depth, exact match (e.g. 16, 32, -32)."],
                    "min_egain": ["type": "number", "description": "Electron conversion factor ≥ this value (e⁻/ADU, FITS EGAIN)."],
                    "max_egain": ["type": "number", "description": "Electron conversion factor ≤ this value (e⁻/ADU, FITS EGAIN)."],
                    "min_position_angle": ["type": "number", "description": "Field rotation position angle ≥ this value (degrees east of north)."],
                    "max_position_angle": ["type": "number", "description": "Field rotation position angle ≤ this value (degrees east of north)."],
                    "added_after": ["type": "string", "description": "Only frames added to the archive on or after this date (YYYY-MM-DD)."],
                    "added_before": ["type": "string", "description": "Only frames added to the archive on or before this date (YYYY-MM-DD)."],
                    "max_fwhm": ["type": "number", "description": "Only frames with median FWHM ≤ this value (pixels). Frames without quality data are excluded."],
                    "min_stars": ["type": "integer", "description": "Only frames with at least this many detected stars. Frames without quality data are excluded."],
                    "max_background_noise": ["type": "number", "description": "Only frames with background noise ≤ this value (ADU for frames processed with quality pipelines). Frames without quality data are excluded."],
                    "max_eccentricity": ["type": "number", "description": "Only frames with median star eccentricity ≤ this value (0=circular). Frames without quality data are excluded."],
                    "max_saturated_star_count": ["type": "integer", "description": "At most this many saturated stars."],
                    "max_hot_pixel_count": ["type": "integer", "description": "At most this many hot pixels (calibration frames)."],
                    "max_sun_altitude": ["type": "number", "description": "Sun altitude at capture time ≤ this value (degrees; use -18 for astronomical night)."],
                    "min_moon_separation": ["type": "number", "description": "Moon separation from target ≥ this value (degrees)."],
                    "max_moon_illumination": ["type": "number", "description": "Moon illumination ≤ this fraction (0–1)."],
                    "is_master": ["type": "boolean", "description": "When true return only master calibration frames; when false exclude them."],
                    "session_id": ["type": "string", "description": "Return only frames belonging to this observing session UUID."],
                ] as [String: Any],
                "required": [],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_create",
            "description": "Create a named frame set by querying the archive. All matched frames must share the same frame type and processing level. Mixed optical filters are blocked by default — set force=true to allow them (stored as a comma-separated list). Rejected frames are automatically excluded. Always returns the inspection report alongside the new set.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "name": ["type": "string", "description": "Name for the frame set. Auto-generated from query parameters if omitted."],
                    "frame_type": ["type": "string", "enum": ["light", "dark", "flat", "bias", "diagnostic"], "description": "Frame type to include (required — a set is homogeneous)."],
                    "object_name": ["type": "string", "description": "Partial object name to match (e.g. 'M51')."],
                    "filters": ["type": "array", "items": ["type": "string"], "description": "Optical filters to include (Hɑ, SII, OIII, R, G, B, L)."],
                    "camera": ["type": "string", "description": "Camera name (exact match)."],
                    "telescope": ["type": "string", "description": "Telescope name, exact match (FITS TELESCOP)."],
                    "site": ["type": "string", "description": "Observatory site name, exact match (FITS OBSERVAT)."],
                    "min_focal_length": ["type": "number", "description": "Focal length ≥ this value (mm)."],
                    "max_focal_length": ["type": "number", "description": "Focal length ≤ this value (mm)."],
                    "min_aperture": ["type": "number", "description": "Telescope aperture ≥ this value (mm, FITS APTDIA)."],
                    "max_aperture": ["type": "number", "description": "Telescope aperture ≤ this value (mm, FITS APTDIA)."],
                    "min_pixel_size": ["type": "number", "description": "Physical (unbinned) pixel size ≥ this value (µm)."],
                    "max_pixel_size": ["type": "number", "description": "Physical (unbinned) pixel size ≤ this value (µm)."],
                    "binning": ["type": "integer", "description": "Pixel binning factor, exact match (FITS XBINNING; 1 = unbinned)."],
                    "gain": ["type": "number", "description": "Camera gain setting, exact match (FITS GAIN)."],
                    "offset": ["type": "number", "description": "Camera offset/pedestal setting, exact match (FITS OFFSET/PEDESTAL)."],
                    "min_exposure": ["type": "number", "description": "Exposure time ≥ this value (seconds)."],
                    "max_exposure": ["type": "number", "description": "Exposure time ≤ this value (seconds)."],
                    "from_date": ["type": "string", "description": "Start date YYYY-MM-DD."],
                    "to_date": ["type": "string", "description": "End date YYYY-MM-DD."],
                    "processing_level": ["type": "string", "enum": ["raw", "calibrated", "stacked", "stretched"], "description": "Filter by processing level."],
                    "calibrated": ["type": "boolean", "description": "Only calibrated frames."],
                    "temp_center": ["type": "number", "description": "Centre temperature in °C for dark frame grouping."],
                    "temp_tolerance": ["type": "number", "description": "Temperature tolerance ±°C (default 2.0)."],
                    "min_pixel_scale": ["type": "number", "description": "Pixel scale ≥ this value (arcsec/px)."],
                    "max_pixel_scale": ["type": "number", "description": "Pixel scale ≤ this value (arcsec/px)."],
                    "min_width": ["type": "integer", "description": "Image width ≥ this value (pixels)."],
                    "max_width": ["type": "integer", "description": "Image width ≤ this value (pixels)."],
                    "min_height": ["type": "integer", "description": "Image height ≥ this value (pixels)."],
                    "max_height": ["type": "integer", "description": "Image height ≤ this value (pixels)."],
                    "bitpix": ["type": "integer", "description": "FITS BITPIX bit depth, exact match (e.g. 16, 32, -32)."],
                    "min_egain": ["type": "number", "description": "Electron conversion factor ≥ this value (e⁻/ADU, FITS EGAIN)."],
                    "max_egain": ["type": "number", "description": "Electron conversion factor ≤ this value (e⁻/ADU, FITS EGAIN)."],
                    "min_position_angle": ["type": "number", "description": "Field rotation position angle ≥ this value (degrees east of north)."],
                    "max_position_angle": ["type": "number", "description": "Field rotation position angle ≤ this value (degrees east of north)."],
                    "added_after": ["type": "string", "description": "Only frames added to the archive on or after this date (YYYY-MM-DD)."],
                    "added_before": ["type": "string", "description": "Only frames added to the archive on or before this date (YYYY-MM-DD)."],
                    "max_fwhm": ["type": "number", "description": "Only frames with median FWHM ≤ this value (pixels). Frames without quality data are excluded."],
                    "min_stars": ["type": "integer", "description": "Only frames with at least this many detected stars. Frames without quality data are excluded."],
                    "max_background_noise": ["type": "number", "description": "Only frames with background noise ≤ this value (ADU for frames processed with quality pipelines). Frames without quality data are excluded."],
                    "max_eccentricity": ["type": "number", "description": "Only frames with median star eccentricity ≤ this value (0=circular). Frames without quality data are excluded."],
                    "max_saturated_star_count": ["type": "integer", "description": "At most this many saturated stars."],
                    "max_hot_pixel_count": ["type": "integer", "description": "At most this many hot pixels (calibration frames)."],
                    "max_sun_altitude": ["type": "number", "description": "Sun altitude at capture time ≤ this value (degrees; use -18 for astronomical night)."],
                    "min_moon_separation": ["type": "number", "description": "Moon separation from target ≥ this value (degrees)."],
                    "max_moon_illumination": ["type": "number", "description": "Moon illumination ≤ this fraction (0–1)."],
                    "is_master": ["type": "boolean", "description": "When true return only master calibration frames; when false exclude them."],
                    "session_id": ["type": "string", "description": "Return only frames belonging to this observing session UUID."],
                    "force": ["type": "boolean", "description": "Allow mixed optical filters; stored as comma-separated list on the frame set (default false)."],
                ] as [String: Any],
                "required": ["frame_type"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_get",
            "description": "Get details of a frame set, including its member frames.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Frame set UUID."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_quality",
            "description": "Display a per-frame quality summary for a frame set (star count, FWHM, eccentricity, background noise). Quality metrics are read from the archive; run ap-archive frameset quality <id> or ap run frame_quality --input @frameset:<id> first to populate them.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Frame set UUID."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_add",
            "description": "Add frames to an existing frame set. Frames must match the set's frame type, processing level, optical filter, and the query criteria the set was created with; frames exceeding the set's quality thresholds are added but marked excluded. Frames already in the set are skipped. Set force=true to bypass the filter and criteria checks (type and level must still match).",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "frameset_id": ["type": "string", "description": "Frame set UUID."],
                    "frame_ids": ["type": "array", "items": ["type": "string"], "description": "Frame UUIDs to add."],
                    "force": ["type": "boolean", "description": "Skip the filter and creation-criteria checks (default false)."],
                ] as [String: Any],
                "required": ["frameset_id", "frame_ids"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_remove",
            "description": "Remove frames from a frame set. The frames themselves stay in the archive. Removing all remaining members is refused — use archive_frameset_delete instead.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "frameset_id": ["type": "string", "description": "Frame set UUID."],
                    "frame_ids": ["type": "array", "items": ["type": "string"], "description": "Frame UUIDs to remove."],
                ] as [String: Any],
                "required": ["frameset_id", "frame_ids"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_exclude",
            "description": "Mark a frame as excluded within a specific frame set. Excluded frames are skipped during processing but remain in the set. Unlike the global reject flag, this is specific to one frame set.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "frameset_id": ["type": "string", "description": "Frame set UUID."],
                    "frame_id":    ["type": "string", "description": "Frame UUID to exclude."],
                    "reason":      ["type": "string", "description": "Optional reason for exclusion."],
                    "undo":        ["type": "boolean", "description": "Set to true to re-include the frame (clear the excluded flag)."],
                ] as [String: Any],
                "required": ["frameset_id", "frame_id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frameset_delete",
            "description": "Delete a frame set. Member frames are not removed from the archive.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Frame set UUID."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_recent",
            "description": "List the most recently added items in the archive, newest first. By default returns a mixed activity feed (mode=\"sessions\"); pass mode=\"frames\" to get individual frames instead.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "limit": [
                        "type": "integer",
                        "description": "Maximum number of items to return (default: 15); 0 or negative returns all.",
                    ],
                    "mode": [
                        "type": "string",
                        "enum": ["sessions", "frames"],
                        "description": "What to list: \"sessions\" (default) returns a mixed activity feed — observing sessions for GPS-tagged raw frames, UTC-date groups for raw frames without site coordinates, processed frames individually, and framesets; \"frames\" returns individual raw frames only.",
                    ],
                ] as [String: Any],
                "required": [],
            ] as [String: Any],
        ],
        [
            "name": "archive_remove",
            "description": "Remove a frame from the archive by its UUID.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Archive frame UUID."],
                    "delete_file": ["type": "boolean", "description": "Also delete the FITS file from disk."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_reject",
            "description": "Mark a frame as rejected (excluded from processing) or clear the rejection flag.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Archive frame UUID."],
                    "reason": ["type": "string", "description": "Optional reason for rejection."],
                    "undo": ["type": "boolean", "description": "Set to true to clear the rejection flag (un-reject)."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_update_stretch",
            "description": "Save or clear the display stretch settings for an archived frame. The stretch is stored as two independent pieces: (1) normalization bounds (input_black / input_white) — the sub-range that was mapped to [0, 1] when the user pressed Normalize; and (2) slider positions (slider_black / slider_white) — where the black/white-point sliders currently sit within [0, 1] of the full data range. Both are independent of bit depth and sensor gain. Pass reset: true to clear everything. The underlying FITS file is never modified.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id":           ["type": "string",  "description": "Archive frame UUID."],
                    "input_black":  ["type": "number",  "description": "Normalized [0, 1] normalization black bound. Must be < input_white."],
                    "input_white":  ["type": "number",  "description": "Normalized [0, 1] normalization white bound. Must be > input_black."],
                    "slider_black": ["type": "number",  "description": "Black-point slider in [0, 1] of the full data range (independent of the normalization bounds)."],
                    "slider_white": ["type": "number",  "description": "White-point slider in [0, 1] of the full data range (independent of the normalization bounds)."],
                    "reset":        ["type": "boolean", "description": "When true, clears all stretch and slider state. Overrides all other parameters."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_update_quality",
            "description": "Update quality metrics for an archived frame. Metrics are normally populated automatically after running a quality pipeline (frame_quality for light frames, calibration_quality for dark/bias/flat) via run_pipeline. Use this tool to set or correct them manually. Only supplied fields are updated; omitted fields are unchanged.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Archive frame UUID."],
                    "star_count": ["type": "integer", "description": "Number of detected stars (light frames)."],
                    "saturated_star_count": ["type": "integer", "description": "Number of saturated stars (peak ≥ 90 % full-scale)."],
                    "median_fwhm": ["type": "number", "description": "Median FWHM in pixels (average of major and minor axes)."],
                    "background_noise": ["type": "number", "description": "Background level in ADU (light frames, frame_quality pipeline) or noise sigma in ADU (calibration frames, calibration_quality pipeline). Legacy pipelines store a normalised 0–1 value."],
                    "median_eccentricity": ["type": "number", "description": "Median star eccentricity (0=circular, closer to 0 is rounder). Indicates optical quality and tracking accuracy."],
                    "hot_pixel_count": ["type": "integer", "description": "Approximate count of hot pixels (calibration frames, from calibration_quality pipeline)."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_backfill_metadata",
            "description": "Re-read FITS headers for existing archived frames and fill in missing metadata. Fills observation strings (OBJECT → objectName, INSTRUME → camera, TELESCOP → telescope, OBSERVAT → site) and numeric acquisition data (EXPTIME → exposureTime, GAIN → gain, OFFSET → offset, CCD-TEMP → temperature, EGAIN → egain, FOCALLEN → focalLength, PIXSCALE → pixelScale, POSANGLE → positionAngle). When no explicit scale keyword exists, pixelScale is derived from XPIXSZ × XBINNING / FOCALLEN. Framesets whose member frames now agree on a pixel scale are filled in as well. Only fills fields that are currently nil — existing values are never overwritten. When exposureTime is recovered the frame's deduplication signature is recomputed. By default only raw frames are processed; pass include_stacked: true to also include calibrated and stacked frames.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "include_stacked": ["type": "boolean", "description": "Also process calibrated and stacked frames (default: false, raw only)."],
                ] as [String: Any],
                "required": [],
            ] as [String: Any],
        ],
        [
            "name": "archive_frame_lineage",
            "description": "Show the full version history for a pipeline result frame. Returns the lineage chain from newest to oldest, with a diff between each consecutive pair showing which pipeline parameters changed, how many input frames were added or removed, and how quality metrics (FWHM, star count, eccentricity, background noise) changed.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "id": ["type": "string", "description": "Archive frame UUID to retrieve lineage for."],
                ] as [String: Any],
                "required": ["id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_sessions",
            "description": "List observing sessions, newest first. Without arguments returns all sessions (light and calibration). Use date to filter to one night, latest_count to get the N most recent, and kind to restrict by type.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "date":         ["type": "string",  "description": "Calendar date YYYY-MM-DD. Returns light sessions whose night started on this date."],
                    "latest_count": ["type": "integer", "description": "Return only the N most recent light sessions. Omit for all."],
                    "kind":         ["type": "string",  "enum": ["all", "night", "day", "calibration"], "description": "Filter by session type: 'all' returns light + calibration sessions; 'calibration' returns dark/flat/bias sessions only (default: all)."],
                ] as [String: Any],
                "required": [],
            ] as [String: Any],
        ],
        [
            "name": "archive_backfill_sessions",
            "description": "Assign observing sessions to raw light frames that already have site coordinates and a timestamp but have not been grouped into a session yet. Safe to run multiple times — already-assigned frames are skipped.",
            "inputSchema": [
                "type": "object",
                "properties": [String: Any](),
                "required": [],
            ] as [String: Any],
        ],
        [
            "name": "archive_session_frames",
            "description": "List the raw frames that belong to a session (light or calibration), ordered by timestamp.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "session_id": ["type": "string", "description": "UUID of the session."],
                ] as [String: Any],
                "required": ["session_id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_frame_session",
            "description": "Return the session (light or calibration) a raw frame belongs to. Returns null if the frame has no session assigned or is not a raw frame.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "frame_id": ["type": "string", "description": "UUID of the frame."],
                ] as [String: Any],
                "required": ["frame_id"],
            ] as [String: Any],
        ],
        [
            "name": "archive_set_pixel_scale",
            "description": "Bulk-set the pixel scale (arcsec/px) on all archived frames and framesets matching a telescope and/or camera (exact names as stored in the archive — check archive_search output). Use this for frames whose FITS headers carry neither a scale keyword nor the optics keywords needed to derive one. Pass arcsec_per_pixel directly, or focal_length_mm + pixel_size_um (+ optional binning) to compute it as 206.265 × pixel_size × binning / focal_length. By default only fills missing (nil) values; pass overwrite: true to replace existing ones. Stacked frames and framesets inherit equipment names from their inputs, so they are updated by the same call.",
            "inputSchema": [
                "type": "object",
                "properties": [
                    "arcsec_per_pixel": ["type": "number", "description": "Image scale in arcseconds per pixel. Either this or focal_length_mm + pixel_size_um is required."],
                    "focal_length_mm":  ["type": "number", "description": "Telescope focal length in mm (used with pixel_size_um when arcsec_per_pixel is not given)."],
                    "pixel_size_um":    ["type": "number", "description": "Unbinned sensor pixel size in µm (used with focal_length_mm)."],
                    "binning":          ["type": "integer", "description": "Binning factor for the computed scale (default: 1)."],
                    "telescope":        ["type": "string", "description": "Exact telescope name to match (FITS TELESCOP). At least one of telescope/camera is required."],
                    "camera":           ["type": "string", "description": "Exact camera name to match (FITS INSTRUME). At least one of telescope/camera is required."],
                    "overwrite":        ["type": "boolean", "description": "Replace existing pixel scales too (default: false, only fills missing values)."],
                ] as [String: Any],
                "required": [],
            ] as [String: Any],
        ],
    ]
}
