import Foundation

// Called by the VersionPlugin build tool plugin.
// Usage: version-tool <version-txt-path> <output-swift-path>
guard CommandLine.arguments.count == 3 else {
    fputs("usage: version-tool <version.txt> <Version.generated.swift>\n", stderr)
    exit(1)
}

let versionFilePath = CommandLine.arguments[1]
let outputPath      = CommandLine.arguments[2]

// Read major.minor.patch from version.txt
let versionString = (try? String(contentsOfFile: versionFilePath, encoding: .utf8))?
    .trimmingCharacters(in: .whitespacesAndNewlines) ?? "0.0.0"

let parts = versionString.split(separator: ".").compactMap { Int($0) }
let major = parts.count > 0 ? parts[0] : 0
let minor = parts.count > 1 ? parts[1] : 0
let patch = parts.count > 2 ? parts[2] : 0

// Query git for build number (total commit count) and short hash.
func git(_ args: String...) -> String {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/git")
    proc.arguments = args
    proc.currentDirectoryURL = URL(fileURLWithPath: versionFilePath)
        .deletingLastPathComponent()
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError  = Pipe()
    try? proc.run()
    proc.waitUntilExit()
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    return String(data: data, encoding: .utf8)?
        .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
}

let build  = Int(git("rev-list", "--count", "HEAD")) ?? 0
let commit = git("rev-parse", "--short", "HEAD")

let output = """
// Auto-generated by VersionPlugin — do not edit.
public enum Version {
    public static let major:  Int    = \(major)
    public static let minor:  Int    = \(minor)
    public static let patch:  Int    = \(patch)
    public static let build:  Int    = \(build)
    public static let commit: String = "\(commit)"
    public static let string: String = "\(major).\(minor).\(patch)+\(build)"
}
"""

try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
